# Generated by Django 5.0.6 on 2024-06-21 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anketApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeOrInternship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=1024)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('PRACTICE', 'Practice'), ('INTERNSHIP', 'Internship')], max_length=20)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anketApp.mentorform')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anketApp.studentform')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=1024)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('AGREEMENT', 'Agreement'), ('STAFF', 'staff')], max_length=20)),
                ('position', models.CharField(max_length=1024)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anketApp.mentorform')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anketApp.studentform')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
