# Generated by Django 5.0.6 on 2024-06-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='type',
            field=models.CharField(choices=[('AGREEMENT', 'Agreement'), ('STAFF', 'Staff')], max_length=20),
        ),
    ]
