# Generated by Django 5.0.6 on 2024-06-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anketApp', '0001_initial'),
        ('hardskillApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorform',
            name='hard_skills_id',
        ),
        migrations.RemoveField(
            model_name='studentform',
            name='hard_skills_id',
        ),
        migrations.AddField(
            model_name='mentorform',
            name='hard_skills_id',
            field=models.ManyToManyField(to='hardskillApp.hardskill'),
        ),
        migrations.AddField(
            model_name='studentform',
            name='hard_skills_id',
            field=models.ManyToManyField(to='hardskillApp.hardskill'),
        ),
    ]
