# Generated by Django 5.0.6 on 2024-06-24 08:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anketApp', '0003_remove_studentform_end_study_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentform',
            name='end_study_year',
            field=models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AlterField(
            model_name='studentform',
            name='start_study_year',
            field=models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)]),
        ),
    ]
