# Generated by Django 5.0.6 on 2024-06-24 08:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anketApp', '0004_alter_studentform_end_study_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentform',
            name='end_study_year',
            field=models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AlterField(
            model_name='studentform',
            name='start_study_year',
            field=models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)]),
        ),
    ]
