# Generated by Django 5.0.6 on 2024-07-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anket_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentoranket',
            name='gender',
            field=models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], max_length=7),
        ),
        migrations.AlterField(
            model_name='studentanket',
            name='gender',
            field=models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], max_length=7),
        ),
    ]
