# Generated by Django 5.0.6 on 2024-07-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='type',
            field=models.CharField(choices=[('Практика', 'Практика'), ('Стажировка', 'Стажировка')], max_length=20),
        ),
        migrations.AlterField(
            model_name='work',
            name='type',
            field=models.CharField(choices=[('Договор', 'Договор'), ('Штаб', 'Штаб')], max_length=20),
        ),
    ]
